# Generated by Django 5.1 on 2024-08-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='songwriter',
            new_name='songwriters',
        ),
    ]
